#baseURL: "https://andreynautilus.github.io/"
title: Andrey Nautilus blog
theme: PaperMod

pagination:
  pagerSize: 10  # number of posts per page

titleCaseStyle: none  # do not capitalize titles

# Configure for publishing on GitHub Pages
cleanDestinationDir: true
publishDir: docs

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

# googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

outputs:
  home:
    - html
    - json

params:
  env: production  # to enable google analytics, opengraph, twitter-cards and schema.
  title: Andrey Nautilus blog
  description: Andrey Nautilus blog
  keywords: [Blog, Portfolio, PaperMod]
  # author: Me  # no author info - everything is authored by me
  # images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto  # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: false  # hide share buttons for posts for now
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: false  # word count is useless, "reading time" is enough
  ShowRssButtonInSectionTermList: false  # no RSS feeds for now
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  # assets:
  #   # disableHLJS: true # to disable highlight.js
  #   # disableFingerprinting: true
  #   favicon: "<link / abs url>"
  #   favicon16x16: "<link / abs url>"
  #   favicon32x32: "<link / abs url>"
  #   apple_touch_icon: "<link / abs url>"
  #   safari_pinned_tab: "<link / abs url>"

  label:
    text: "Andrey Nautilus blog"
    icon: /apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: false  # needs to be explicitly set
    # title: ExampleSite
    # subtitle: "This is subtitle"
    # imageUrl: "<img location>"
    # imageWidth: 120
    # imageHeight: 120
    # imageTitle: my image
    # buttons:
    #   - name: Posts
    #     url: posts
    #   - name: Tags
    #     url: tags

  # home-info mode
  homeInfoParams:
    Title: "Welcome"
    Content: >-
      Explore hidden features of tools, procedural generation tips,
      and software engineering insights.

  socialIcons:
    - name: linkedin
      url: "https://www.linkedin.com/in/andrey-potapov-1049b096/"
    - name: github
      url: "https://github.com/AndreyNautilus"

  # analytics:
  #   google:
  #     SiteVerificationTag: "XYZabc"
  #   bing:
  #     SiteVerificationTag: "XYZabc"
  #   yandex:
  #     SiteVerificationTag: "XYZabc"

  cover:
    hidden: true  # hide everywhere but not in structured data
    hiddenInList: true  # hide on list pages and home
    hiddenInSingle: true  # hide on single page

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    limit: 10  # refer: https://www.fusejs.io/api/methods.html#search
    keys: ["title", "permalink", "summary", "content"]

menu:
  main:
    - name: links
      weight: 1
      url: links/
    - name: tags
      weight: 2
      url: tags/
    - name: search
      weight: 5
      url: search/
    - name: src
      weight: 10
      url: https://github.com/AndreyNautilus/AndreyNautilus.github.io

# https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai
